-- Doelenboom platform — seed data
-- Demo-doelenboom "Gezond ouder" (tenant Demo) voor een fictief verzorgingshuis.
-- Bewust geen echte KMar/FPBB-data (meer) — die hoort niet op een gedeelde
-- productieomgeving thuis. Idempotent: draait alleen iets als tenant 'demo'
-- nog niet bestaat (init.sql-conventie: dit bestand wordt alleen bij de
-- allereerste containerstart uitgevoerd door Postgres zelf, dus de guard
-- hieronder is vooral bedoeld voor handmatig herdraaien tijdens ontwikkeling).
do $$
begin
  -- Losstaande guard (i.p.v. onderdeel van het tenant-blok hieronder): dit
  -- bestand moet ook veilig herdraaid kunnen worden tegen een database die
  -- al eerder is geïnitialiseerd -- bv. handmatig via psql om de Demo-tenant
  -- alsnog toe te voegen aan een productie-database die oorspronkelijk met
  -- een oudere seed is gestart (zie deploy/README.md). De sysadmin-account
  -- bestaat dan al; alleen de tenant/doelenboom hieronder is dan nieuw.
  if not exists (select 1 from users where email = 'admin@code072.nl') then
    insert into users (email, password_hash, is_sysadmin)
    values ('admin@code072.nl', crypt('changeme', gen_salt('bf')), true);
  end if;

  if not exists (select 1 from tenants where slug = 'demo') then

    insert into tenants (slug, name) values ('demo', 'Demo');

    insert into doelenbomen (tenant_id, slug, name)
    select id, 'gezond-ouder', 'Gezond ouder' from tenants where slug = 'demo';

    -- column_configs / columns — de tenant-default (sjabloon voor eventuele
    -- nieuwe doelenbomen bij deze tenant) én de eigen config van de
    -- gezond-ouder-boom zelf. Zonder deze twee rijen toont tree.html een
    -- volledig lege kolommenweergave (elk element wordt dan als "onbekend
    -- type" overgeslagen, zie buildColumnsHtml() in web/public/tree.html) —
    -- dit bestand omzeilt bewust de normale aanmaakroutes
    -- (createTenantDefaultConfig/createDoelenboomConfigFromTenantDefault in
    -- api/src/columnConfig.ts), dus die twee rijen moeten hier expliciet
    -- gezaaid worden. Zelfde 8 standaardkolommen als standardColumns('Demo').
    insert into column_configs (scope, tenant_id)
    values ('tenant_default', (select id from tenants where slug = 'demo'));
    insert into column_configs (scope, tenant_id, doelenboom_id)
    values ('doelenboom', (select id from tenants where slug = 'demo'), (select id from doelenbomen where slug = 'gezond-ouder'));

    insert into columns (column_config_id, position, type_name, title, subtitle, color, is_narrow, node_font_size, is_project_role, relation_label_to_next)
    select cc.id, v.position, v.type_name, v.title, v.subtitle, v.color, v.is_narrow, v.node_font_size, v.is_project_role, v.relation_label_to_next
    from column_configs cc
    cross join (values
      (0, 'Project', 'Project', 'Welke projecten ontwikkelen deze capability?', '#3E6FA6', true, null::int, true, 'ontwikkelt'),
      (1, 'Capability', 'Capability', 'Welk vermogen wordt hiermee opgebouwd?', '#6B4C8A', true, null::int, false, 'ondersteunt'),
      (2, 'Operationele benefit', 'Operationele benefit', 'Welke operationele verbetering levert dit op? Wat verandert er in de dagelijkse uitvoering?', '#C05A2C', false, null::int, false, 'realiseert'),
      (3, 'Sub-benefit', 'Sub-benefit Demo', 'Welk direct effect ontstaat hierdoor?', '#B8862E', false, null::int, false, 'versterkt'),
      (4, 'Programmabaat', 'Programmabaat Demo', 'Welke waarde levert dit aan Demo?', '#2E7D5B', false, null::int, false, 'draagt bij aan'),
      (5, 'Strategische benefit', 'Strategisch benefit Demo', 'Wat betekent dit voor Demo?', '#8FAADC', false, 10, false, 'ondersteunt'),
      (6, 'Strategisch doel', 'Strategisch doel', 'Welk doel ondersteunt dit?', '#2F5597', false, 12, false, 'geeft invulling aan'),
      (7, 'Missie', 'Missie Demo', 'Waarom doen we dit uiteindelijk?', '#203864', false, 10, false, null)
    ) as v(position, type_name, title, subtitle, color, is_narrow, node_font_size, is_project_role, relation_label_to_next)
    where cc.tenant_id = (select id from tenants where slug = 'demo');

    -- elements
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'M1', 'Missie', 'Gezond ouder worden door gezamenlijk lichamelijk en geestelijk te blijven bewegen', 'De missie van het verzorgingshuis: bewoners zo lang en zo prettig mogelijk vitaal houden, samen — niet alleen door beweging, maar ook door sociale verbondenheid en geestelijke activiteit. Dit vormt het hoogste anker van de doelenboom: alle onderliggende doelen, benefits en programmabaten moeten hier aantoonbaar aan bijdragen.', '', '-', '', '', 0);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SD1', 'Strategisch doel', 'Bewoners blijven langer lichamelijk vitaal', 'Bewoners behouden zo lang mogelijk hun lichamelijke zelfredzaamheid en mobiliteit, met minder functieverlies en minder valincidenten.', 'Missie', 'Gemiddelde ADL-zelfredzaamheidsscore bewoners', '', '', 1);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SD2', 'Strategisch doel', 'Bewoners blijven langer geestelijk actief en sociaal verbonden', 'Bewoners blijven cognitief actief en ervaren minder eenzaamheid, door sociale en geestelijk uitdagende activiteiten.', 'Missie', 'Gemiddelde welzijns-/eenzaamheidsscore bewoners', '', '', 2);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SB1', 'Strategische benefit', 'Minder valincidenten en functieverlies', 'Door gerichte preventie en beweging lopen bewoners minder risico op vallen en op geleidelijk functieverlies.', 'SD1', '% minder valincidenten t.o.v. vorig jaar', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 3);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SB2', 'Strategische benefit', 'Hogere deelname aan beweegactiviteiten', 'Meer bewoners nemen structureel deel aan beweegactiviteiten die passen bij hun mogelijkheden.', 'SD1', '% bewoners dat wekelijks deelneemt aan beweegactiviteiten', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 4);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SB3', 'Strategische benefit', 'Minder eenzaamheid en meer sociale interactie', 'Bewoners hebben meer sociale contactmomenten en voelen zich minder eenzaam.', 'SD2', 'Score eenzaamheidsschaal (verkorte UCLA-schaal)', 'Zorg & Welzijn', 'Sociaal & cognitief', 5);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'SB4', 'Strategische benefit', 'Behoud van cognitieve vaardigheden', 'Bewoners behouden langer hun geheugen- en denkvaardigheden door gerichte training en uitdaging.', 'SD2', 'Gemiddelde MMSE-score bewoners', 'Zorg & Welzijn', 'Sociaal & cognitief', 6);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'PB1', 'Programmabaat', 'Beweegprogramma "Actief Blijven"', 'Een samenhangend programma van dagelijks beweegaanbod en valpreventie, gericht op behoud van lichamelijke vitaliteit.', 'SB1 primair; SB2 primair', 'Samengestelde vitaliteitsindex', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 7);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'PB2', 'Programmabaat', 'Programma "Samen Actief"', 'Een samenhangend programma van sociale, creatieve en cognitieve activiteiten, gericht op verbondenheid en geestelijke vitaliteit.', 'SB3 primair; SB4 primair', 'Samengestelde welzijns-/cognitie-index', 'Zorg & Welzijn', 'Sociaal & cognitief', 8);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'OB1', 'Operationele benefit', 'Dagelijks beweegaanbod beschikbaar voor alle bewoners', 'Elke bewoner heeft toegang tot een passend, dagelijks beweegaanbod, ongeacht mobiliteitsniveau.', 'PB1', '% bewoners met toegang tot dagelijks beweegaanbod', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 9);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'OB2', 'Operationele benefit', 'Vroegsignalering van valrisico', 'Valrisico bij bewoners wordt tijdig herkend en beoordeeld, zodat preventieve maatregelen op tijd genomen kunnen worden.', 'PB1', '% bewoners met actuele valrisicoscreening', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 10);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'OB3', 'Operationele benefit', 'Wekelijkse sociale en creatieve activiteiten', 'Er is een vast, aantrekkelijk aanbod van sociale en creatieve activiteiten waaraan bewoners kunnen deelnemen.', 'PB2', '% bewoners dat wekelijks deelneemt aan sociale activiteiten', 'Zorg & Welzijn', 'Sociaal & cognitief', 11);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'OB4', 'Operationele benefit', 'Individuele geheugentraining beschikbaar', 'Bewoners die dat nodig hebben krijgen toegang tot individuele geheugen- en cognitieve training.', 'PB2', '% bewoners met individueel geheugentrainingsaanbod', 'Zorg & Welzijn', 'Sociaal & cognitief', 12);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'C1', 'Capability', 'Beweeg- en fysiotherapiecapaciteit', 'Vermogen om voldoende gekwalificeerde beweeg- en fysiotherapiebegeleiding te organiseren en beschikbaar te stellen.', 'OB1', 'Beschikbare fysiotherapie-/beweegcoachcapaciteit (fte)', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 13);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'C2', 'Capability', 'Valrisicoscreening en -monitoring', 'Vermogen om valrisico structureel te screenen, monitoren en te vertalen naar preventieve maatregelen.', 'OB2', '% bewoners met tijdig herhaalde valrisicoscreening', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 14);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'C3', 'Capability', 'Activiteitenbegeleiding en vrijwilligerscoördinatie', 'Vermogen om een aantrekkelijk activiteitenaanbod te organiseren met voldoende begeleiding en vrijwilligers.', 'OB3', 'Aantal actieve vrijwilligers per bewoner', 'Zorg & Welzijn', 'Sociaal & cognitief', 15);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'C4', 'Capability', 'Cognitieve trainingsprogramma''s', 'Vermogen om passende geheugen- en cognitieve trainingsprogramma''s te ontwikkelen en aan te bieden.', 'OB4', 'Aantal beschikbare geheugentrainingsmodules', 'Zorg & Welzijn', 'Sociaal & cognitief', 16);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'P1', 'Project', 'Inrichten beweegtuin en gymzaal', 'Aanleg van een buiten-beweegtuin en inrichting van een binnen-gymzaal, geschikt voor bewoners met uiteenlopende mobiliteit.', 'C1', 'Projectvoortgang en oplevercriteria volgens het projectplan', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 17);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'P2', 'Project', 'Implementatie valrisico-screeningstool', 'Invoering van een digitale tool waarmee zorgmedewerkers valrisico structureel en gestandaardiseerd screenen.', 'C2', 'Projectvoortgang en oplevercriteria volgens het projectplan', 'Zorg & Welzijn', 'Lichamelijke vitaliteit', 18);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'P3', 'Project', 'Vrijwilligersprogramma "Samen Actief"', 'Opzetten en werven van een vast vrijwilligersnetwerk dat wekelijkse sociale en creatieve activiteiten mede organiseert.', 'C3', 'Projectvoortgang en oplevercriteria volgens het projectplan', 'Zorg & Welzijn', 'Sociaal & cognitief', 19);
    insert into elements (doelenboom_id, code, type, name, description, parent_text, kpi, taakveld, subtaakveld, sort_order) values ((select id from doelenbomen where slug='gezond-ouder'), 'P4', 'Project', 'Pilot geheugentraining-app', 'Pilot met een tablet-app voor individuele, laagdrempelige geheugentraining onder begeleiding van activiteitenbegeleiders.', 'C4', 'Projectvoortgang en oplevercriteria volgens het projectplan', 'Zorg & Welzijn', 'Sociaal & cognitief', 20);

    -- edges (kind -> ouder, net als bij de rest van het platform)
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='M1'), NULL, '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='M1'), NULL, '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB3'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB4'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SD2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB3'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB4'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB3'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB4'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='PB2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C3'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB3'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C4'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB4'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P1'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C1'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P2'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C2'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P3'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C3'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;
    insert into edges (doelenboom_id, source_element_id, target_element_id, weight, toelichting) values ((select id from doelenbomen where slug='gezond-ouder'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P4'), (select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='C4'), 'primair', '') on conflict (source_element_id, target_element_id) do nothing;

    -- project_status
    insert into project_status (element_id, projectstatus, rag, toelichting, gerapporteerd_op) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P1'), 'Actief', 'Groen', 'Aanbesteding gegund, bouw gestart', current_date - interval '5 days');
    insert into project_status (element_id, projectstatus, rag, toelichting, gerapporteerd_op) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P2'), 'Actief', 'Oranje', 'Vertraging door leverancier van de screeningstool', current_date - interval '5 days');
    insert into project_status (element_id, projectstatus, rag, toelichting, gerapporteerd_op) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P3'), 'Gereed', 'Groen', 'Afgerond en overgedragen aan de activiteitenbegeleiding', current_date - interval '30 days');
    insert into project_status (element_id, projectstatus, rag, toelichting, gerapporteerd_op) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P4'), 'Backlog', '', '', NULL);

    -- products
    insert into products (element_id, code, name, omschrijving, pct_gereed, verwachte_datum, werkelijke_datum, opmerking) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P1'), 'PR001', 'Beweegtuin buitenterrein', 'Buitenruimte met beweegtoestellen geschikt voor ouderen.', 60, current_date + interval '45 days', NULL, '');
    insert into products (element_id, code, name, omschrijving, pct_gereed, verwachte_datum, werkelijke_datum, opmerking) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P2'), 'PR002', 'Digitale screeningstool', 'Tablet-toepassing voor gestandaardiseerde valrisicoscreening door zorgmedewerkers.', 40, current_date + interval '60 days', NULL, 'Wacht op testomgeving van de leverancier');
    insert into products (element_id, code, name, omschrijving, pct_gereed, verwachte_datum, werkelijke_datum, opmerking) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P3'), 'PR003', 'Vrijwilligersnetwerk "Samen Actief"', 'Vast netwerk van getrainde vrijwilligers dat wekelijkse activiteiten mede organiseert.', 100, current_date - interval '35 days', current_date - interval '30 days', '');

    -- tags
    insert into tags (doelenboom_id, code, name, categorie, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'T1', 'Vitaliteit', 'Thema', 'Gericht op lichamelijke vitaliteit en valpreventie.');
    insert into tags (doelenboom_id, code, name, categorie, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'T2', 'Sociaal', 'Thema', 'Gericht op sociale verbondenheid en geestelijke activiteit.');
    insert into tags (doelenboom_id, code, name, categorie, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'T3', 'Innovatie', 'Thema', 'Vernieuwende, digitale aanpak binnen het programma.');

    -- element_tags
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB1'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T1'), '');
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB2'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T1'), '');
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB3'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T2'), '');
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='SB4'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T2'), '');
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P2'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T3'), '');
    insert into element_tags (element_id, tag_id, toelichting) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='P4'), (select id from tags where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='T3'), '');

    -- org_units
    insert into org_units (doelenboom_id, code, name, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'ORG1', 'Fysiotherapie', '');
    insert into org_units (doelenboom_id, code, name, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'ORG2', 'Activiteitenbegeleiding', '');
    insert into org_units (doelenboom_id, code, name, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'ORG3', 'Zorg', '');
    insert into org_units (doelenboom_id, code, name, omschrijving) values ((select id from doelenbomen where slug='gezond-ouder'), 'ORG4', 'Vrijwilligerscoördinatie', '');

    -- ob_org_relations
    insert into ob_org_relations (element_id, org_unit_id, relatietype, toelichting, status) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB1'), (select id from org_units where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='ORG1'), 'Primair', '', 'Gevalideerd');
    insert into ob_org_relations (element_id, org_unit_id, relatietype, toelichting, status) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB2'), (select id from org_units where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='ORG3'), 'Primair', '', 'Gevalideerd');
    insert into ob_org_relations (element_id, org_unit_id, relatietype, toelichting, status) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB3'), (select id from org_units where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='ORG2'), 'Primair', '', 'Gevalideerd');
    insert into ob_org_relations (element_id, org_unit_id, relatietype, toelichting, status) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB3'), (select id from org_units where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='ORG4'), 'Ondersteunend', '', 'Gevalideerd');
    insert into ob_org_relations (element_id, org_unit_id, relatietype, toelichting, status) values ((select id from elements where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='OB4'), (select id from org_units where doelenboom_id=(select id from doelenbomen where slug='gezond-ouder') and code='ORG3'), 'Primair', '', 'Gevalideerd');

  end if;
end $$;
